network_name: vgan-based
img_size: 1024
crop_size: 1024
dataset_name: celeba-1024
image_dir: ./data/celeba-1024
ngpu: 4
g_batch_size: 4
d_batch_size: 12
gen_nums: 3
lr: 0.0001
z_dim: 256
alpha_init: 1
max_step: 250000
critic: 1
save_step: 5
backup_every: 100000
lr_decay: False
lr_decay_every: 100
info_bottle: True
