network_name: vgan-based
img_size: 128
crop_size: 128
dataset_name: celeba
image_dir: ./data/celeba
ngpu: 1
g_batch_size: 6
d_batch_size: 32
gen_nums: 5
lr: 0.0001
z_dim: 256
alpha_init: 1
max_step: 633100
critic: 1
save_step: 5
backup_every: 100000
lr_decay: False
lr_decay_every: 100
info_bottle: False
