network_name: sngan-based
img_size: 32
crop_size: 32
dataset_name: imagenet
image_dir: ./data/imagenet
ngpu: 1
g_batch_size: 12
d_batch_size: 64
gen_nums: 10
lr: 0.0002
z_dim: 128
alpha_init: 1
max_step: 500000
critic: 4
save_step: 5
backup_every: 25000
lr_decay: 100
lr_decay_every: 100
info_bottle: False
